### ISSUE TITLE
🐛 Unable to install Emerald

### ISSUE THREAD

**Issue by Uranite** [RiversideValley/Emerald#35]
### ⏱️ Before you start...

- [X] Are you on the latest version of Emerald? You might be using an old version.
- [X] Have you checked whether or not a similar issue has already been reported?

### 🪟 What build of Windows is this issue present? (optional)

Windows 11 23H2 Build 22631.3447

### 🔢 What version of Emerald are you on?

Version 0.7.8

### 📄 Description

Unable to install with the error message:
>This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

### 🪜 Steps To Reproduce

1. Download Emerald v0.7.8.0 https://github.com/RiversideValley/Emerald/releases/tag/v0.7.8.0
2. Run the .msixbundle file

### 🤔 Expected behavior

I should be able to install Emerald

### 📸 Assets

![image](https://github.com/RiversideValley/Emerald/assets/62639703/066cb6a3-2337-4cd9-90c4-ceac9894aa4f)

**Comment by Lamparter** [comment]
### You need to trust the certificate first before running the MSIX bundle.
*I worked really hard to make this guide - please do not dismiss it just because it looks difficult.*

---
`step 1` - ***go to the properties of the MSIXBUNDLE file***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/37818a73-7c5e-4098-87d3-3fa1a5458bd9)

`step 2` - ***find Digital Signatures***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/9600af61-2d60-49e6-81bc-d9935f03456a)

`step 3` - ***select certificate and press Details***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/29ee2ce2-be93-46d9-af93-2455275274b7)

`step 4` - ***press View Certificate***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/75a02cb9-b6c9-46ca-830d-c329eb5d758d)

`step 5` - ***press Install Certificate...***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/5d9601f0-a909-4205-ac19-0abcc62f4263)

`step 6` - ***press Next***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/79023f9b-fadb-4f0f-86aa-57b0f4a7c974)

`step 7` - ***press Place all certificates in the following store***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/b43b0eca-c68e-44c1-ba47-3e07ce94d070)

`step 8` - ***press Browse... and then select Trusted Publishers***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/169b432d-9993-4e48-962b-0967c9a50aa4)

`step 9` - ***press Next and then Finish***
<br/>
![image](https://github.com/RiversideValley/Emerald/assets/71598437/094c308a-2c4f-40d6-898f-a3b4fd1db294)

**You will then be greeted by this notification box. Close it and run the MSIXBUNDLE file. Please make another comment if this method fails.***

**Comment by Suburbanno** [comment]
@NoobNotFound this method not working for me

win 11
Emerald 7.9.0

**Comment by Lamparter** [comment]
Can you try [*this*](https://gist.github.com/Lamparter/e82b78340fa037931126c363325bd97b) guide instead?

**Comment by Suburbanno** [comment]
> Can you try [_this_](https://gist.github.com/Lamparter/e82b78340fa037931126c363325bd97b) guide instead?

Oh ok, it worked

**Comment by Lamparter** [comment]
Amazing! Closing the issue for now - let me know if you run into any more issues! We're here to help.

**Comment by RandomMonkey99** [comment]
No one of the two works for me

**Comment by Lamparter** [comment]
Emerald development is sort of on pause right now as @NoobNotFound is working hard to port the app to Uno Platform!
I wouldn't recommend installing the app right now.
